# Generated by Django 4.1 on 2022-12-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('publication', models.CharField(max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sagidullin.autors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sagidullin.category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sagidullin.publisher')),
            ],
        ),
    ]
